### ISSUE TITLE
Fails to run (list index out of range when trying to get nixos-config value from NIX_PATH)

### ISSUE THREAD

**Issue by Thra11** [nix-gui/nix-gui#132]
```
 ✘  ~  nix run github:nix-gui/nix-gui nix-gui
Traceback (most recent call last):
  File "/nix/store/mzvpwj8yi7l2kd4i6cyfmb7zbiklb6b7-python3.9-nix-gui-0.1.0/bin/.nix-gui-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/mzvpwj8yi7l2kd4i6cyfmb7zbiklb6b7-python3.9-nix-gui-0.1.0/lib/python3.9/site-packages/nixui/main.py", line 54, in main
    args = handle_args()
  File "/nix/store/mzvpwj8yi7l2kd4i6cyfmb7zbiklb6b7-python3.9-nix-gui-0.1.0/lib/python3.9/site-packages/nixui/main.py", line 20, in handle_args
    nixos_config = os.environ['NIX_PATH'].split(':')[2].split('=')[1]  # TODO: what is the clean way of getting NIX_PATH nixos-config value
IndexError: list index out of range
```
My `NIX_PATH` is `nixos-config=/etc/nixos/configuration.nix:nixpkgs=/home/thrall/nixpkgs/`, so...
```
 ~  python3
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['NIX_PATH']
'nixos-config=/etc/nixos/configuration.nix:nixpkgs=/home/thrall/nixpkgs/'
>>> os.environ['NIX_PATH'].split(':')
['nixos-config=/etc/nixos/configuration.nix', 'nixpkgs=/home/thrall/nixpkgs/']
>>> os.environ['NIX_PATH'].split(':')[1]
'nixpkgs=/home/thrall/nixpkgs/'
>>> os.environ['NIX_PATH'].split(':')[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> os.environ['NIX_PATH'].split(':')[0]
'nixos-config=/etc/nixos/configuration.nix'
```

## System Info:
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.05.20210904.b6d9850 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/home/thrall/nixpkgs`
```

**Comment by lapp0** [comment]
Could you please try `nix run github:nix-gui/nix-gui/fix-132` and confirm whether it works?
