### ISSUE TITLE
UTF-8 supports

### ISSUE THREAD

**Issue by pinage404** [nix-gui/nix-gui#14]
Hello,

I tryied again, it failed again =P

It seems that it does not like a character in a comment
https://gitlab.com/pinage404/dotfiles/-/blob/d1be7b97e47fececa56927446fab0644fabfb563/nixos/machine/gigabyte_sabre_15/configuration.nix#L2

```
CONFIGURATION_PATH=/etc/nixos/configuration.nix nixFlakes run github:lapp0/nix-gui
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
Traceback (most recent call last):
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/parser/ast.py", line 105, in visit_token
    quoted = quoted.encode('utf-8').decode('unicode_escape')  # unescape
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 104-105: truncated \uXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/bin/.nix-gui-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/gui.py", line 66, in main
    statemodel = state_model.StateModel()
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/state_model.py", line 12, in __init__
    self.current_values = api.get_option_values_map()
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/api.py", line 65, in get_option_values_map
    for option, option_data in get_option_data().items()
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/api.py", line 39, in get_option_data
    configured_values = {'.'.join(k): v for k, v in parser.get_all_option_values(os.environ['CONFIGURATION_PATH']).items()}
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/parser/parser.py", line 11, in get_all_option_values
    syntax_tree = ast.get_ast(module_path)
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/parser/ast.py", line 38, in get_ast
    return parse_ast_str(ast_str)
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/parser/ast.py", line 55, in parse_ast_str
    root_node = NixVisitor().visit(tree)
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in <listcomp>
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in <listcomp>
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in <listcomp>
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in <listcomp>
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in <listcomp>
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 227, in visit
    reraise(VisitationError, VisitationError(exc, exc_class, node), tb)
  File "/nix/store/14sil57w425v7ncx8jk9rwb1zz7ix204-python3.8-six-1.15.0/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/nix/store/agjny99n2ny4pc5zn46pima7rabb2ysq-python3.8-parsimonious-0.8.1/lib/python3.8/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/nix/store/fdazal8y5az6vg0z5r8d6wb82ys4j5pi-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/parser/ast.py", line 105, in visit_token
    quoted = quoted.encode('utf-8').decode('unicode_escape')  # unescape
parsimonious.exceptions.VisitationError: UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 104-105: truncated \uXXXX escape

Parse tree:
<Node called "token" matching "TOKEN_COMMENT("# Help is available in the configuration.nix(5) man page and in the NixOS manual (accessible by running \u{2018}nixos-help\u{2019})") 81..202
  ">  <-- *** We were here. ***
    <RegexNode called "name" matching "TOKEN_COMMENT">
    <Node called "lpar" matching "(">
    <RegexNode called "quoted" matching ""# Help is available in the configuration.nix(5) man page and in the NixOS manual (accessible by running \u{2018}nixos-help\u{2019})"">
    <Node called "rpar" matching ")">
    <RegexNode called "ws" matching " ">
    <RegexNode called "numrange" matching "81..202">
    <RegexNode called "ws" matching "
      ">
```

**Comment by lapp0** [comment]
Thanks for the report, should be working in `master` now
