### ISSUE TITLE
label option data with type string and fix search

### ISSUE THREAD

**Issue by lapp0** [nix-gui/nix-gui#179]
```
Traceback (most recent call last):
  File "/nix/store/w35gfhmyw95yx7b5n3lb9759mykw3sqb-python3.9-nix-gui-0.1.2/lib/python3.9/site-packages/nixui/graphics/navbar.py", line 70, in <lambda>
    lambda: set_lookup_key_fn(f'search:{searchbox.text()}')
  File "/nix/store/w35gfhmyw95yx7b5n3lb9759mykw3sqb-python3.9-nix-gui-0.1.2/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 59, in set_lookup_key
    self.set_search_query(search_str)
  File "/nix/store/w35gfhmyw95yx7b5n3lb9759mykw3sqb-python3.9-nix-gui-0.1.2/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 145, in set_search_query
    navlist.SearchResultListDisplay(
  File "/nix/store/w35gfhmyw95yx7b5n3lb9759mykw3sqb-python3.9-nix-gui-0.1.2/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 279, in __init__
    for option_path, matched_operations in self.search_tree_for_options(tree, search_str):
  File "/nix/store/w35gfhmyw95yx7b5n3lb9759mykw3sqb-python3.9-nix-gui-0.1.2/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 327, in search_tree_for_options
    if data._type != option_definition.Undefined and token in data._type.lower():
AttributeError: 'AttrsType' object has no attribute 'lower'
```

**Comment by lapp0** [comment]
fixed by https://github.com/nix-gui/nix-gui/pull/169
