### ISSUE TITLE
error: file 'nixos/modules' was not found in the Nix search path

### ISSUE THREAD

**Issue by milahu** [nix-gui/nix-gui#224]
run nix-gui

```
nix run github:nix-gui/nix-gui
INFO:Retrieving option values for module "/etc/nixos/configuration.nix"
INFO:Retrieving option values for module "/etc/nixos/hardware-configuration.nix"
```

navigate to `environment.systemPackages` and click on the plus button `[ + ]`
(whatever that button is, there is no tooltip)

```
ERROR:NixEvalError("""
error: file 'nixos/modules' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

<details>

trace

```
ERROR:NixEvalError("""
error: file 'nixos/modules' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at /nix/store/5pgzzhbd37vrn7ndxgg1276xj0iic70m-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/nix/lib.nix:4:17:

            3|   inherit (import <nixos> {}) config;
            4|   modulesPath = <nixos/modules>;
             |                 ^
            5| in lib.makeExtensible (self: {

""")
Traceback (most recent call last):
  File "/nix/store/5pgzzhbd37vrn7ndxgg1276xj0iic70m-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/options/option_tree.py", line 263, in children
    children = self.tree.children(attribute)
  File "/nix/store/3rpcl8zn86vry182x86892z4kz2k9rxa-python3.9-treelib-1.6.1/lib/python3.9/site-packages/treelib/tree.py", line 360, in children
    return [self[i] for i in self.is_branch(nid)]
  File "/nix/store/3rpcl8zn86vry182x86892z4kz2k9rxa-python3.9-treelib-1.6.1/lib/python3.9/site-packages/treelib/tree.py", line 500, in is_branch
    raise NodeIDAbsentError("Node '%s' is not in the tree" % nid)
treelib.exceptions.NodeIDAbsentError: Node 'environment.systemPackages.newAttribute' is not in the tree

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/5pgzzhbd37vrn7ndxgg1276xj0iic70m-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 305, in add_clicked
    item = OptionListItem(
  File "/nix/store/5pgzzhbd37vrn7ndxgg1276xj0iic70m-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 115, in __init__
    num_direct_children = len(self.option_tree.children(self.option))
  File "/nix/store/5pgzzhbd37vrn7ndxgg1276xj0iic70m-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/options/option_tree.py", line 269, in children
    raise ValueError()
ValueError
Aborted
```

/etc/nixos/configuration.nix

```nix

{ config, lib, pkgs, ... }:

let
  packageList = with pkgs; [
    gparted
    usbutils # lsusb
    nano
    wget
  ];
in

{
  environment.systemPackages = packageList;
}
```

env

```
sudo nix-channel --list 
nixos https://nixos.org/channels/nixos-21.05

echo $NIX_PATH | tr : '\n'
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
nixos-config=/etc/nixos/configuration.nix
/nix/var/nix/profiles/per-user/root/channels

ls /nix/var/nix/profiles/per-user/root/channels/nixos/modules
No such file or directory

ls /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/
config    i18n       misc             profiles  rename.nix  services  tasks    virtualisation
hardware  installer  module-list.nix  programs  security    system    testing
```

nix repl

```
nix-repl> <nixos/modules>
error: file 'nixos/modules' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixos/modules>
             | ^
            2|

nix-repl> <nixos/nixos/modules>
/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules
```

</details>

**Comment by milahu** [comment]
with #225 nix-gui throws

```
nix run . 

# navigate to environment.systemPackages
# click on the plus button [ + ]

Traceback (most recent call last):
  File "/nix/store/ga4x4k7mxzmv97ws0drgfj63mswg1rbf-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/options/option_tree.py", line 263, in children
    children = self.tree.children(attribute)
  File "/nix/store/3rpcl8zn86vry182x86892z4kz2k9rxa-python3.9-treelib-1.6.1/lib/python3.9/site-packages/treelib/tree.py", line 360, in children
    return [self[i] for i in self.is_branch(nid)]
  File "/nix/store/3rpcl8zn86vry182x86892z4kz2k9rxa-python3.9-treelib-1.6.1/lib/python3.9/site-packages/treelib/tree.py", line 500, in is_branch
    raise NodeIDAbsentError("Node '%s' is not in the tree" % nid)
treelib.exceptions.NodeIDAbsentError: Node 'environment.systemPackages.newAttribute' is not in the tree

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ga4x4k7mxzmv97ws0drgfj63mswg1rbf-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 305, in add_clicked
    item = OptionListItem(
  File "/nix/store/ga4x4k7mxzmv97ws0drgfj63mswg1rbf-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/graphics/navlist.py", line 115, in __init__
    num_direct_children = len(self.option_tree.children(self.option))
  File "/nix/store/ga4x4k7mxzmv97ws0drgfj63mswg1rbf-python3.9-nix-gui-0.1.5/lib/python3.9/site-packages/nixui/options/option_tree.py", line 269, in children
    raise ValueError()
ValueError
Aborted
```

**Comment by lapp0** [comment]
Please try merging https://github.com/nix-gui/nix-gui/pull/229 into your branch. It fixes the regression in dynamic navlists. 

Dynamic navlists are still a WIP (last part of milestone 1)

**Comment by milahu** [comment]
> ```error: file 'nixos/modules' was not found in the Nix search path (add it using $NIX_PATH or -I)```

still an issue on a fresh nixos install

```
$ echo $NIX_PATH | tr : '\n'
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
nixos-config=/etc/nixos/configuration.nix
/nix/var/nix/profiles/per-user/root/channels
```

workaround: nixos=$nixpkgs

```
$ NIX_PATH=$NIX_PATH:nixos=/nix/var/nix/profiles/per-user/root/channels/nixos nix run .
```
