### ISSUE TITLE
KeyError: NIX_PATH

### ISSUE THREAD

**Issue by tripleo1** [nix-gui/nix-gui#282]
```bash
$ nix --experimental-features 'nix-command flakes' run github:nix-gui/nix-gui
Traceback (most recent call last):
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/bin/.nix-gui-wrapped", line 6, in <module>
    from nixui.main import main
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/main.py", line 10, in <module>
    from nixui.options import environment
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/environment.py", line 11, in <module>
    def get_nixos_config_path(nix_path=os.environ['NIX_PATH']):
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'NIX_PATH'

```

Done on Ubuntu 22.10 with fresh nixpkgs:

```
[nix-shell:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0-31-generic, Ubuntu, 22.10 (Kinetic Kudu), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ca5ua1** [comment]
> Using
> 
> Prerequisites:
> 
>     Ensure NixOS is installed
>

**Comment by tripleo1** [comment]
RTFM, copy
