### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Tomes0** [nix-gui/nix-gui#283]
Hey, I've tried to install it using
`nix --experimental-features 'nix-command flakes' run github:nix-gui/nix-gui`

However, I get this error:
```
Traceback (most recent call last):
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 57, in set_lookup_key
    self.set_option_path(
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 91, in set_option_path
    num_children = len(api.get_option_tree().children(option_path, mode="leaves"))
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/utils/cache.py", line 85, in wrapper
    res = function(*args, **kwargs)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/api.py", line 22, in get_option_tree
    return option_tree.OptionTree(
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/option_tree.py", line 68, in __init__
    self._upsert_node_data(
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/option_tree.py", line 99, in _upsert_node_data
    if self._is_attribute_set(parent_option_path) and child_option_path.get_end() != '<name>':
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/option_tree.py", line 120, in _is_attribute_set
    return isinstance(data.get_type(), types.AttrsOfType)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/option_tree.py", line 30, in get_type
    return types.from_nix_type_str(self._type_string)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/types.py", line 31, in from_nix_type_str
    from_nix_type_str(nix_type_str.removeprefix('attribute set of ').removesuffix('s'))
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/options/types.py", line 217, in from_nix_type_str
    raise ValueError(nix_type_str)
ValueError: (submodule)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/bin/.nix-gui-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/main.py", line 69, in main
    run_program()
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/main.py", line 50, in run_program
    nix_gui = main_window.NixGuiMainWindow(statemodel)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/main_window.py", line 17, in __init__
    nav_interface.OptionNavigationInterface(statemodel=statemodel)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 39, in __init__
    self.set_lookup_key(starting_lookup_key)
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 66, in set_lookup_key
    self.revert_to_previous_lookup_key()
  File "/nix/store/vrxvadsl8kzhq8d3cynw08gvvqr4gy3p-python3.9-nix-gui-0.1.6/lib/python3.9/site-packages/nixui/graphics/nav_interface.py", line 46, in revert_to_previous_lookup_key
    previous_uri = self.uri_stack.pop()
IndexError: pop from an empty deque
```

I'm runing NixOS 23.11 and Python 3.9.18

**Comment by StrongSand94191** [comment]
getting the same error on 24.05

**Comment by Xyz00777** [comment]
i sadly think these project is dead :/
